language: r
r:
  - oldrel
  - release
  - devel

cache: packages

r_github_packages:
  - HenrikBengtsson/matrixStats@develop
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(exclusions = list("R/zzz.R"))'
