language: r
sudo: required
warnings_are_errors: true

r_binary_packages:
  - matrixStats
  - knitr
  - testthat

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    - jgabry@gmail.com
